# Generated by Django 3.1.2 on 2022-05-16 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_auto_20220516_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('b', 'black'), ('w', 'white')], default='b', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='factory',
            field=models.ForeignKey(default='benz', on_delete=django.db.models.deletion.CASCADE, to='modelapp.factory'),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='name',
            field=models.CharField(default='benz', max_length=10),
        ),
    ]
